"use strict";

export const REQUEST_SENT = "REQUEST_SENT";
export const REQUEST_RECEIVED_SUCCESSFUL = "REQUEST_RECEIVED_SUCCESSFUL";
export const REQUEST_RECEIVED_ERROR = "REQUEST_RECEIVED_ERROR";

export const DISPATCH_NEWS = "WE_GOT_NEWS";

export const CHECK_ACTIVE_USER = "CHECK_ACTIVE_USER";
export const ACTIVE_USER_CONFIRMED = "ACTIVE_USER_CONFIRMED";

export const CHANGE_DIRECTORY = "CHANGE_DIRECTORY";
export const UPDATE_NEWS_FILTER = "NEWS_UPDATING";
export const NEWS_FILTERS_FROM_STORAGE = "NEWS_FILTERS_FROM_STORAGE";
export const CLEAR_NEWS_FILTERS = "CLEAR_NEWS_FILTERS";

export const ALL_SOURCES_HERE = "ALL_SOURCES_HERE";

