"use strict";

export const REQUEST_SENT = "REQUEST_SENT";
export const REQUEST_RECEIVED_SUCCESSFUL = "REQUEST_RECEIVED_SUCCESSFUL";
export const REQUEST_RECEIVED_ERROR = "REQUEST_RECEIVED_ERROR";

export const DISPATCH_NEWS = "WE_GOT_NEWS";

export const DO_YOU_BELONG_HERE = "YOU_BELONG_HERE?";
export const CHECK_ACTIVE_USER = "CHECK_ACTIVE_USER";
export const ACTIVE_USER_CONFIRMED = "ACTIVE_USER_CONFIRMED";
export const LOGOUT_USER = "BYE_BYE";

export const CHANGE_DIRECTORY = "CHANGE_DIRECTORY";
export const UPDATE_NEWS_FILTER = "NEWS_UPDATING";